_target_: experiment_utils.utils_hydra.load_partial_func
function: ranger21.Ranger21
lr: 0.001
lookahead_active: True
lookahead_mergetime: 5
lookahead_blending_alpha: 0.5
lookahead_load_at_validation: False
use_madgrad: False
use_adabelief: False
softplus: True
beta_softplus: 50
using_gc: True
using_normgc: True
gc_conv_only: False
normloss_active: True
normloss_factor: 1e-4
use_adaptive_gradient_clipping: True
agc_clipping_value: 1e-2
agc_eps: 1e-3
betas: [0.9, 0.999]  # temp for checking tuned warmups
momentum_type: pnm
pnm_momentum_factor: 1.0
momentum: 0.9
eps: 1e-8

num_batches_per_epoch: None
num_epochs: None
use_cheb: False
use_warmup: True
num_warmup_iterations: None

warmdown_active: True
warmdown_start_pct: 0.72
warmdown_min_lr: 3e-5
weight_decay: 1e-4
decay_type: stable
warmup_type: linear
warmup_pct_default: 0.22
logging_active: True