model_load: True
model_path: /Data/model_weights/
file_name: xse_resnext50_weight_0
with_opt: False
se_name: False
process_model:
  _target_: experiment_utils.utils.hydra_utils.load_func
  function_path: local_utils.model_constructor.process_model
  function: change_head_pool
  fc_name: False
  head_lin: head_lin_0
  bn_pool: True
  bn_end: False
  bn_first: False
