_target_: experiment_utils.utils.hydra_utils.load_partial_func
function: experiment_utils.utils.fastai_utils.fit_warmap_anneal

defaults:
  - cbs: empty_list

anneal_type: cos
anneal_div: 1e5
anneal_pct: 0.75
wd: 0
# power: 1 # add +power if use "poly" annealing