_target_: experiment_utils.utils.hydra_utils.load_partial_func
function: experiment_utils.utils.fastai_utils.fit_anneal_warmap

defaults:
  - cbs: empty_list

annealing_type: lin
div_final: 1e5
pct_start: 0.75
wd: 0