_target_: pt_utils.utils_hydra.load_partial_func
function: experiment_utils.fastai_utils.fit_anneal_warmap

pct_warmup: 0.05  # 0.
div_warmup: 10  # 1
warmup_type: cos

annealing_type: cos
div_final: 1e5
pct_start: 0.75
wd: 0
power: 1