_target_: experiment_utils.utils.fastai_utils.dls_pt_timm

train_data_path: ${data.data_dir}/train
val_data_path: ${data.data_dir}/val

batch_size: ${data.batch_size}
size: ${data.size}
num_workers: ${data.dataloader.num_workers}
pin_memory: False  # True
shuffle: True
shuffle_val: False
drop_last: True
persistent_workers: False
color_jitter: 0

limit_dataset: False
# scale: (0.35, 1.)

image_backend: PIL

augmix: False
num_splits: 2