_target_: experiment_utils.utils.fastai_utils.dls_from_pytorch

defaults:
  - train_tfms: train_tfms
  - val_tfms: val_tfms

train_data_path: ${data.data_dir}/train
val_data_path: ${data.data_dir}/val

batch_size: ${data.batch_size}
num_workers: ${data.dataloader.num_workers}
pin_memory: False  # True
shuffle: True
shuffle_val: False
drop_last: True
persistent_workers: False

image_backend: PIL