# _target_: local_utils.model_constructor.mtanh.MultTanh
_target_: experiment_utils.utils.hydra_utils.class_obj
class_name: local_utils.model_constructor.xrelu.SReLu
min: 0.8
mult_min: 0.01
negative: False