# _target_: local_utils.model_constructor.mtanh.MultTanh
_target_: experiment_utils.utils.hydra_utils.class_obj
# class_name: local_utils.model_constructor.xrelu.xMish
class_name: local_utils.model_constructor.act_fn.xMish
min_mult: 1.
