# _target_: local_utils.model_constructor.mtanh.MultTanh
_target_: experiment_utils.utils.hydra_utils.class_obj
class_name: local_utils.model_constructor.xrelu.XReLu
min: 0.8
max: 0.8
mult_max: 0.01
mult_min: 0.01